# Parcial N°1 - Analisis de Datos COM3

### Integrantes:
* Pablo Vivas
* Lisandro Romero
* Tobias Rivas
* Morgui Mateo
* Diaz Manuel
* Diaz Sebastian

# Preguntas
* Qué tipos de automotores fueron los más transferidos en enero de 2025?
* ¿Qué marcas registraron la mayor cantidad de transferencias?
* En qué provincias se concentraron más transferencias?
* ¿Qué marcas lideran en cada provincia?
* ¿Qué tipo de automotor predomina según la provincia?
* persona juridica y personas fisicas
* 2 propuestas de marketing de autos que no se estan vendiendo

In [95]:
## Importacion de archivo csv
import pandas as pd
import numpy as np

df_csv_original = pd.read_csv('tranferencias_autos.csv')

cantidad_de_datos_duplicados= df_csv_original.duplicated().sum()

cantidad_de_datos_nulos = df_csv_original.isnull().sum()

print("-----DATOS DUPLICADOS-----")
print(cantidad_de_datos_duplicados)
print("")
print("-----DATOS NULOS-----")
print(cantidad_de_datos_nulos)

C:\Users\elviv\AppData\Local\Temp\ipykernel_9396\3274668864.py:5: DtypeWarning: Columns (0: titular_anio_nacimiento) have mixed types. Specify dtype option on import or set low_memory=False.
  df_csv_original = pd.read_csv('tranferencias_autos.csv')

-----DATOS DUPLICADOS-----
338

-----DATOS NULOS-----
tramite_tipo                         0
tramite_fecha                        0
fecha_inscripcion_inicial            0
registro_seccional_codigo            0
registro_seccional_descripcion      44
registro_seccional_provincia        44
automotor_origen                     0
automotor_anio_modelo              794
automotor_tipo_codigo             3797
automotor_tipo_descripcion           0
automotor_marca_codigo            1266
automotor_marca_descripcion          0
automotor_modelo_codigo           2184
automotor_modelo_descripcion         0
automotor_uso_codigo                 6
automotor_uso_descripcion            6
titular_tipo_persona                 0
titular_domicilio_localidad          6
titular_domicilio_provincia          0
titular_genero                       0
titular_anio_nacimiento              0
titular_pais_nacimiento              0
titular_porcentaje_titularidad       0
titular_domicilio_provincia_id       0
titular_pais_nacimiento_id        9612
dtype: int64

In [96]:
print("-----LIMPIAZA DE DATOS-----")
df_csv_filtrado = df_csv_original.drop_duplicates()

print("Cantidad de filas despues de la purga de datos duplicados:", len(df_csv_filtrado))

print("")

# No se menciona en la busqueda pero hay datos nulos en el año de nacimiento del titular

# Preguntar que hacer con las personas juridicas (Empresas) ya que hacen que tengan datos nulos en algunos id
# como por ejemplo los paises de nacimiento

# Hay datos nulos en automotor_marca_codigo que serian demaciado dificil de encontrar, que hacemos

print("")
print("Se investigo y descubrio que los datos nullos de las columnas registro_seccional_descripcion")
print("y registro_seccional_provincia pertenecen a Buenos Aires, Avellaneda nº7")

print("")
# Arreglo de seccion y provincia
df_csv_filtrado['registro_seccional_descripcion'] = df_csv_filtrado['registro_seccional_descripcion'].fillna('AVELLANEDA Nº7')
df_csv_filtrado['registro_seccional_provincia'] = df_csv_filtrado['registro_seccional_provincia'].fillna('Buenos Aires')

# Arreglo de uso a no declarado como el resto 
df_csv_filtrado['automotor_uso_codigo'] = df_csv_filtrado['automotor_uso_codigo'].fillna(9)
df_csv_filtrado['automotor_uso_descripcion'] = df_csv_filtrado['automotor_uso_descripcion'].fillna('No declarado')

# Rellenado de datos nulos
df_csv_filtrado['automotor_anio_modelo'] = df_csv_filtrado['automotor_anio_modelo'].fillna('No especificado')
df_csv_filtrado['automotor_tipo_codigo'] = df_csv_filtrado['automotor_tipo_codigo'].fillna('No especificado')
df_csv_filtrado['automotor_marca_codigo'] = df_csv_filtrado['automotor_marca_codigo'].fillna('No especificado')
df_csv_filtrado['automotor_modelo_codigo'] = df_csv_filtrado['automotor_modelo_codigo'].fillna('No especificado')
df_csv_filtrado['titular_domicilio_localidad'] = df_csv_filtrado['titular_domicilio_localidad'].fillna('-')
df_csv_filtrado['titular_pais_nacimiento_id'] = df_csv_filtrado['titular_pais_nacimiento_id'].fillna('No especificado')

print("Conteo de nulos por columna despues del arreglo:")
print(df_csv_filtrado.isnull().sum())

-----LIMPIAZA DE DATOS-----
Cantidad de filas despues de la purga de datos duplicados: 169767


Se investigo y descubrio que los datos nullos de las columnas registro_seccional_descripcion
y registro_seccional_provincia pertenecen a Buenos Aires, Avellaneda nº7

Conteo de nulos por columna despues del arreglo:
tramite_tipo                      0
tramite_fecha                     0
fecha_inscripcion_inicial         0
registro_seccional_codigo         0
registro_seccional_descripcion    0
registro_seccional_provincia      0
automotor_origen                  0
automotor_anio_modelo             0
automotor_tipo_codigo             0
automotor_tipo_descripcion        0
automotor_marca_codigo            0
automotor_marca_descripcion       0
automotor_modelo_codigo           0
automotor_modelo_descripcion      0
automotor_uso_codigo              0
automotor_uso_descripcion         0
titular_tipo_persona              0
titular_domicilio_localidad       0
titular_domicilio_provincia       0
titular_genero                    0
titular_anio_nacimiento           0
titular_pais_nacimiento           0
titular_porcentaje_titularidad    0
titular_domicilio_provincia_id    0
titular_pais_nacimiento_id        0
dtype: int64

In [97]:
print("-----SECCION DE PREGUNTAS DE NEGOCIO-----")

print("")
print("-----TIPOS DE AUTOMOTORES MAS TRANSFERIDOS-----")
df_cantidad_tipo = df_csv_filtrado['automotor_tipo_descripcion'].value_counts()
display(df_cantidad_tipo)

print("")
print("-----MARCAS CON MAYOR CANTIDAD DE TRANSFERENCIAS-----")
df_cantidad_marca = df_csv_filtrado['automotor_marca_descripcion'].value_counts()
display(df_cantidad_marca)

print("")
print("-----PROVINCIAS CON MAYOR CANTIDAD DE TRANSFERENCIAS-----")
df_cantidad_provincia = df_csv_filtrado['registro_seccional_provincia'].value_counts()
display(df_cantidad_provincia)

print("")
print("-----MARCAS DE AUTO QUE LIDERAN EN PROVINCIAS CON MAYOR CANTIDAD DE TRANSFERENCIAS-----")
cantidad_marca_provincia = df_csv_filtrado.groupby(['registro_seccional_provincia', 'automotor_marca_descripcion']).size().reset_index(name='cantidad_marca')
marcas = cantidad_marca_provincia.loc[cantidad_marca_provincia.groupby('registro_seccional_provincia')['cantidad_marca'].idxmax()]
display(marcas)

print("")
print("-----TIPO DE AUTO QUE LIDERAN EN PROVINCIAS CON MAYOR CANTIDAD DE TRANSFERENCIAS-----")
cantidad_tipo_provincia = df_csv_filtrado.groupby(['registro_seccional_provincia', 'automotor_tipo_descripcion']).size().reset_index(name='cantidad_modelo')
tipo = cantidad_tipo_provincia.loc[cantidad_tipo_provincia.groupby('registro_seccional_provincia')['cantidad_modelo'].idxmax()]
display(tipo)

print("")
print("-----TITULAR DEL VEHICULO, FISICA O JURIDICA-----")
df_titular = df_csv_filtrado['titular_tipo_persona'].value_counts()
display(df_titular)

-----SECCION DE PREGUNTAS DE NEGOCIO-----

-----TIPOS DE AUTOMOTORES MAS TRANSFERIDOS-----

automotor_tipo_descripcion
SEDAN 5 PUERTAS         36657
SEDAN 4 PUERTAS         21371
SEDAN 5 PTAS            19272
PICK-UP                 18477
SEDAN 4 PTAS            15423
                        ...
CARROZADO C/CAMIONET        1
PICK-UP-DOBLE CABINA        1
SEDAN  5 PUERTAS            1
ARAUS                       1
BUGGI PLAYERO               1
Name: count, Length: 995, dtype: int64

-----MARCAS CON MAYOR CANTIDAD DE TRANSFERENCIAS-----

automotor_marca_descripcion
VOLKSWAGEN                        30453
FORD                              23537
RENAULT                           19820
CHEVROLET                         19749
FIAT                              17625
                                  ...
FIAT INNOCENTI                        1
GMC CHEVETTE (GENERAL MOTORS C        1
ZANELLO                               1
DODGE GTX                             1
HYNDAI                                1
Name: count, Length: 473, dtype: int64

-----PROVINCIAS CON MAYOR CANTIDAD DE TRANSFERENCIAS-----

registro_seccional_provincia
Buenos Aires                       64419
Córdoba                            19599
Ciudad Autónoma de Buenos Aires    15069
Santa Fe                           14060
Mendoza                             8421
Entre Ríos                          6953
Neuquén                             4516
Río Negro                           3628
Tucumán                             3510
Corrientes                          3350
Chubut                              3331
Misiones                            2810
Chaco                               2793
La Pampa                            2639
Salta                               2343
San Luis                            2274
San Juan                            2253
Santa Cruz                          1696
Jujuy                               1290
Santiago del Estero                 1171
Tierra del Fuego                    1020
Formosa                              950
Catamarca                            842
La Rioja                             830
Name: count, dtype: int64

-----MARCAS DE AUTO QUE LIDERAN EN PROVINCIAS CON MAYOR CANTIDAD DE TRANSFERENCIAS-----

,registro_seccional_provincia,automotor_marca_descripcion,cantidad_marca
292,Buenos Aires,VOLKSWAGEN,12360
338,Catamarca,VOLKSWAGEN,154
390,Chaco,VOLKSWAGEN,558
408,Chubut,FORD,616
592,Ciudad Autónoma de Buenos Aires,VOLKSWAGEN,2338
668,Corrientes,VOLKSWAGEN,667
824,Córdoba,VOLKSWAGEN,3137
933,Entre Ríos,VOLKSWAGEN,1376
966,Formosa,TOYOTA,270
1006,Jujuy,VOLKSWAGEN,214
1065,La Pampa,VOLKSWAGEN,541
1099,La Rioja,VOLKSWAGEN,175
1219,Mendoza,VOLKSWAGEN,1348
1269,Misiones,VOLKSWAGEN,542
1332,Neuquén,VOLKSWAGEN,864
1404,Río Negro,VOLKSWAGEN,624
1452,Salta,VOLKSWAGEN,562
1511,San Juan,VOLKSWAGEN,365
1564,San Luis,VOLKSWAGEN,430
1577,Santa Cruz,FORD,308
1769,Santa Fe,VOLKSWAGEN,2159
1816,Santiago del Estero,VOLKSWAGEN,254
1863,Tierra del Fuego,VOLKSWAGEN,134
1924,Tucumán,VOLKSWAGEN,682

-----TIPO DE AUTO QUE LIDERAN EN PROVINCIAS CON MAYOR CANTIDAD DE TRANSFERENCIAS-----

,registro_seccional_provincia,automotor_tipo_descripcion,cantidad_modelo
552,Buenos Aires,SEDAN 5 PUERTAS,13410
680,Catamarca,SEDAN 5 PUERTAS,216
746,Chaco,SEDAN 5 PUERTAS,592
843,Chubut,SEDAN 5 PUERTAS,595
1038,Ciudad Autónoma de Buenos Aires,SEDAN 5 PUERTAS,4483
1133,Corrientes,SEDAN 5 PUERTAS,654
1312,Córdoba,SEDAN 5 PUERTAS,4536
1458,Entre Ríos,SEDAN 5 PUERTAS,1228
1508,Formosa,SEDAN 5 PUERTAS,220
1550,Jujuy,SEDAN 5 PUERTAS,291
1629,La Pampa,SEDAN 5 PUERTAS,512
1673,La Rioja,SEDAN 5 PUERTAS,188
1801,Mendoza,SEDAN 5 PUERTAS,1404
1889,Misiones,SEDAN 5 PUERTAS,509
1970,Neuquén,SEDAN 5 PUERTAS,915
2063,Río Negro,SEDAN 5 PUERTAS,668
2132,Salta,SEDAN 5 PUERTAS,579
2206,San Juan,SEDAN 5 PUERTAS,452
2282,San Luis,SEDAN 5 PUERTAS,476
2338,Santa Cruz,SEDAN 5 PUERTAS,304
2493,Santa Fe,SEDAN 5 PUERTAS,2927
2565,Santiago del Estero,SEDAN 5 PUERTAS,258
2612,Tierra del Fuego,SEDAN 5 PUERTAS,299
2678,Tucumán,SEDAN 5 PUERTAS,941

-----TITULAR DEL VEHICULO, FISICA O JURIDICA-----

titular_tipo_persona
Física      160505
Jurídica      9262
Name: count, dtype: int64